local ADDON_NAME, ns = ...

local locale = GetLocale()

local translations = {
    enUS = {
        ADDON_TITLE = "FastRenown",
        ADDON_DESC = "Shows Renown for the current expansion as a minimap tooltip.",
        SHOW_MINIMAP_BUTTON = "Show minimap button",
        LOCK_MINIMAP_BUTTON = "Lock minimap button",
        RESET_SETTINGS = "Reset settings",
        TOOLTIP_TITLE = "Renown",
        TOOLTIP_RENOWN = "Renown factions for this expansion:",
        RENOWN_LEVEL_FORMAT = "Renown %d",
        TOOLTIP_NONE = "No Renown factions found.",
        TOOLTIP_LOCKED = "Button is locked",
        TOOLTIP_UNLOCKED = "Button can be moved on the minimap",
    },

    deDE = {
        ADDON_TITLE = "FastRenown",
        ADDON_DESC = "Zeigt den Ruhm der aktuellen Erweiterung als Tooltip an der Minimap.",
        SHOW_MINIMAP_BUTTON = "Minimap-Button anzeigen",
        LOCK_MINIMAP_BUTTON = "Minimap-Button sperren",
        RESET_SETTINGS = "Zurücksetzen",
        TOOLTIP_TITLE = "Ruhm",
        TOOLTIP_RENOWN = "Ruhm-Fraktionen dieser Erweiterung:",
        RENOWN_LEVEL_FORMAT = "Ruhm %d",
        TOOLTIP_NONE = "Keine Ruhm-Fraktionen gefunden.",
        TOOLTIP_LOCKED = "Button ist gesperrt",
        TOOLTIP_UNLOCKED = "Button kann an der Minimap verschoben werden",
    },

    frFR = {
        ADDON_TITLE = "FastRenown",
        ADDON_DESC = "Affiche le renom de l’extension actuelle dans une info-bulle sur la minicarte.",
        SHOW_MINIMAP_BUTTON = "Afficher le bouton de minicarte",
        LOCK_MINIMAP_BUTTON = "Verrouiller le bouton de minicarte",
        RESET_SETTINGS = "Réinitialiser les paramètres",
        TOOLTIP_TITLE = "Renom",
        TOOLTIP_RENOWN = "Factions de renom de cette extension :",
        RENOWN_LEVEL_FORMAT = "Renom %d",
        TOOLTIP_NONE = "Aucune faction de renom trouvée.",
        TOOLTIP_LOCKED = "Le bouton est verrouillé",
        TOOLTIP_UNLOCKED = "Le bouton peut être déplacé sur la minicarte",
    },

    esES = {
        ADDON_TITLE = "FastRenown",
        ADDON_DESC = "Muestra el Renombre de la expansión actual en un tooltip del minimapa.",
        SHOW_MINIMAP_BUTTON = "Mostrar botón del minimapa",
        LOCK_MINIMAP_BUTTON = "Bloquear botón del minimapa",
        RESET_SETTINGS = "Restablecer ajustes",
        TOOLTIP_TITLE = "Renombre",
        TOOLTIP_RENOWN = "Facciones de renombre de esta expansión:",
        RENOWN_LEVEL_FORMAT = "Renombre %d",
        TOOLTIP_NONE = "No se encontraron facciones de renombre.",
        TOOLTIP_LOCKED = "El botón está bloqueado",
        TOOLTIP_UNLOCKED = "El botón puede moverse en el minimapa",
    },

    esMX = {
        ADDON_TITLE = "FastRenown",
        ADDON_DESC = "Muestra el Renombre de la expansión actual en un tooltip del minimapa.",
        SHOW_MINIMAP_BUTTON = "Mostrar botón del minimapa",
        LOCK_MINIMAP_BUTTON = "Bloquear botón del minimapa",
        RESET_SETTINGS = "Restablecer ajustes",
        TOOLTIP_TITLE = "Renombre",
        TOOLTIP_RENOWN = "Facciones de renombre de esta expansión:",
        RENOWN_LEVEL_FORMAT = "Renombre %d",
        TOOLTIP_NONE = "No se encontraron facciones de renombre.",
        TOOLTIP_LOCKED = "El botón está bloqueado",
        TOOLTIP_UNLOCKED = "El botón puede moverse en el minimapa",
    },

    itIT = {
        ADDON_TITLE = "FastRenown",
        ADDON_DESC = "Mostra la Fama dell'espansione attuale in un tooltip sulla minimappa.",
        SHOW_MINIMAP_BUTTON = "Mostra pulsante minimappa",
        LOCK_MINIMAP_BUTTON = "Blocca pulsante minimappa",
        RESET_SETTINGS = "Reimposta impostazioni",
        TOOLTIP_TITLE = "Fama",
        TOOLTIP_RENOWN = "Fazioni della fama di questa espansione:",
        RENOWN_LEVEL_FORMAT = "Fama %d",
        TOOLTIP_NONE = "Nessuna fazione fama trovata.",
        TOOLTIP_LOCKED = "Il pulsante è bloccato",
        TOOLTIP_UNLOCKED = "Il pulsante può essere spostato sulla minimappa",
    },

    ptBR = {
        ADDON_TITLE = "FastRenown",
        ADDON_DESC = "Mostra o Renome da expansão atual em uma dica no minimapa.",
        SHOW_MINIMAP_BUTTON = "Mostrar botão no minimapa",
        LOCK_MINIMAP_BUTTON = "Travar botão do minimapa",
        RESET_SETTINGS = "Redefinir configurações",
        TOOLTIP_TITLE = "Renome",
        TOOLTIP_RENOWN = "Facções de Renome desta expansão:",
        RENOWN_LEVEL_FORMAT = "Renome %d",
        TOOLTIP_NONE = "Nenhuma facção de Renome encontrada.",
        TOOLTIP_LOCKED = "O botão está travado",
        TOOLTIP_UNLOCKED = "O botão pode ser movido no minimapa",
    },

    ruRU = {
        ADDON_TITLE = "FastRenown",
        ADDON_DESC = "Показывает известность текущего дополнения во всплывающей подсказке у миникарты.",
        SHOW_MINIMAP_BUTTON = "Показывать кнопку у миникарты",
        LOCK_MINIMAP_BUTTON = "Закрепить кнопку у миникарты",
        RESET_SETTINGS = "Сбросить настройки",
        TOOLTIP_TITLE = "Известность",
        TOOLTIP_RENOWN = "Фракции известности этого дополнения:",
        RENOWN_LEVEL_FORMAT = "Известность %d",
        TOOLTIP_NONE = "Фракции известности не найдены.",
        TOOLTIP_LOCKED = "Кнопка закреплена",
        TOOLTIP_UNLOCKED = "Кнопку можно перемещать по миникарте",
    },

    koKR = {
        ADDON_TITLE = "FastRenown",
        ADDON_DESC = "현재 확장팩의 평판을 미니맵 툴팁으로 표시합니다.",
        SHOW_MINIMAP_BUTTON = "미니맵 버튼 표시",
        LOCK_MINIMAP_BUTTON = "미니맵 버튼 잠금",
        RESET_SETTINGS = "설정 초기화",
        TOOLTIP_TITLE = "평판",
        TOOLTIP_RENOWN = "현재 확장팩의 평판 세력:",
        RENOWN_LEVEL_FORMAT = "평판 %d",
        TOOLTIP_NONE = "평판 세력을 찾지 못했습니다.",
        TOOLTIP_LOCKED = "버튼이 잠겨 있습니다",
        TOOLTIP_UNLOCKED = "버튼은 미니맵에서 이동할 수 있습니다",
    },

    zhCN = {
        ADDON_TITLE = "FastRenown",
        ADDON_DESC = "在小地图提示中显示当前资料片的名望。",
        SHOW_MINIMAP_BUTTON = "显示小地图按钮",
        LOCK_MINIMAP_BUTTON = "锁定小地图按钮",
        RESET_SETTINGS = "重置设置",
        TOOLTIP_TITLE = "名望",
        TOOLTIP_RENOWN = "当前资料片的名望阵营：",
        RENOWN_LEVEL_FORMAT = "名望 %d",
        TOOLTIP_NONE = "未找到名望阵营。",
        TOOLTIP_LOCKED = "按钮已锁定",
        TOOLTIP_UNLOCKED = "按钮可在小地图上移动",
    },

    zhTW = {
        ADDON_TITLE = "FastRenown",
        ADDON_DESC = "在小地圖提示中顯示目前資料片的名望。",
        SHOW_MINIMAP_BUTTON = "顯示小地圖按鈕",
        LOCK_MINIMAP_BUTTON = "鎖定小地圖按鈕",
        RESET_SETTINGS = "重設設定",
        TOOLTIP_TITLE = "名望",
        TOOLTIP_RENOWN = "目前資料片的名望陣營：",
        RENOWN_LEVEL_FORMAT = "名望 %d",
        TOOLTIP_NONE = "找不到名望陣營。",
        TOOLTIP_LOCKED = "按鈕已鎖定",
        TOOLTIP_UNLOCKED = "按鈕可在小地圖上移動",
    },
}

ns.L = translations[locale] or translations.enUS
